/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UIComponents;

import Server.RequestResponseMessenger;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.net.Socket;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Sundu
 */
public class admin extends javax.swing.JFrame {

    /**
     * Creates new form admin
     * 
     */
    
    String fn,ln,add,cit,cntry,a;
        String sAcc1,cAcc1,aType;
        int ssn1,pin1,cbal,sbal;
        Calendar date;
        String uid,contact;
        
    public admin(RequestResponseMessenger obj) {
        initComponents();
  }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        displayName = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        create = new javax.swing.JButton();
        view = new javax.swing.JButton();
        freeze = new javax.swing.JButton();
        basePanel = new javax.swing.JPanel();
        firstPanel = new javax.swing.JPanel();
        ScrollPanel = new javax.swing.JScrollPane();
        Panel4 = new javax.swing.JPanel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        country1 = new javax.swing.JTextField();
        fname1 = new javax.swing.JTextField();
        jLabel49 = new javax.swing.JLabel();
        lname1 = new javax.swing.JTextField();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        accType1 = new javax.swing.JComboBox();
        addr1 = new javax.swing.JTextField();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        cAcc2 = new javax.swing.JTextField();
        city1 = new javax.swing.JTextField();
        jLabel54 = new javax.swing.JLabel();
        state1 = new javax.swing.JTextField();
        createButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        ssn2 = new javax.swing.JTextField();
        uidVar1 = new javax.swing.JLabel();
        uid1 = new javax.swing.JTextField();
        pin2 = new javax.swing.JLabel();
        pinText1 = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        sAcc2 = new javax.swing.JTextField();
        dateChooserCombo1 = new datechooser.beans.DateChooserCombo();
        Panel3 = new javax.swing.JPanel();
        jLabel36 = new javax.swing.JLabel();
        uidText = new javax.swing.JTextField();
        freezeButton = new javax.swing.JButton();
        Panel21 = new javax.swing.JPanel();
        cbText = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        sbText = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        addrText = new javax.swing.JTextArea();
        jButton3 = new javax.swing.JButton();
        jLabel30 = new javax.swing.JLabel();
        cntText = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        cAcc = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        nameText = new javax.swing.JTextField();
        savings = new javax.swing.JLabel();
        sAcc = new javax.swing.JTextField();
        Panel2 = new javax.swing.JPanel();
        jLabel37 = new javax.swing.JLabel();
        jTextField32 = new javax.swing.JTextField();
        retrieveButton = new javax.swing.JButton();
        icon = new javax.swing.JLabel();
        logoutButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(740, 700));

        displayName.setFont(new java.awt.Font("Lucida Grande", 0, 70)); // NOI18N
        displayName.setForeground(new java.awt.Color(255, 153, 153));
        displayName.setText("Piggy Bank");

        create.setText("Create");
        create.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createActionPerformed(evt);
            }
        });

        view.setText("View");
        view.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewActionPerformed(evt);
            }
        });

        freeze.setText("Freeze");
        freeze.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                freezeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(create, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(view, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(freeze))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(create)
                .addGap(71, 71, 71)
                .addComponent(view)
                .addGap(103, 103, 103)
                .addComponent(freeze)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        basePanel.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout firstPanelLayout = new javax.swing.GroupLayout(firstPanel);
        firstPanel.setLayout(firstPanelLayout);
        firstPanelLayout.setHorizontalGroup(
            firstPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 516, Short.MAX_VALUE)
        );
        firstPanelLayout.setVerticalGroup(
            firstPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 528, Short.MAX_VALUE)
        );

        basePanel.add(firstPanel, "card2");

        jLabel46.setText("Country : ");

        jLabel47.setText("First Name :");

        jLabel49.setText("Last Name :");

        jLabel50.setText("Account Type :");

        jLabel51.setText("Address :");

        accType1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Choose one", "Checkings", "Savings", "Both" }));

        jLabel52.setText("Checkings AccNo. :");

        jLabel53.setText("City :");

        jLabel54.setText("State :");

        createButton1.setText("Create");
        createButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createButton1ActionPerformed(evt);
            }
        });

        jLabel4.setText("DOB :");

        jLabel5.setText("SSN");

        ssn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ssn2ActionPerformed(evt);
            }
        });

        uidVar1.setText("User ID:");

        pin2.setText("PIN : ");

        jLabel6.setText("Savings AccNo.:");

        javax.swing.GroupLayout Panel4Layout = new javax.swing.GroupLayout(Panel4);
        Panel4.setLayout(Panel4Layout);
        Panel4Layout.setHorizontalGroup(
            Panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(createButton1)
                .addContainerGap())
            .addGroup(Panel4Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(Panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel47)
                    .addComponent(jLabel49)
                    .addComponent(jLabel51)
                    .addComponent(jLabel53)
                    .addComponent(jLabel54)
                    .addComponent(jLabel46)
                    .addComponent(jLabel50)
                    .addComponent(jLabel52)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(uidVar1)
                    .addComponent(pin2)
                    .addComponent(jLabel6))
                .addGap(268, 268, 268)
                .addGroup(Panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(state1)
                        .addComponent(fname1)
                        .addComponent(lname1)
                        .addComponent(addr1)
                        .addComponent(city1)
                        .addComponent(country1)
                        .addComponent(cAcc2)
                        .addComponent(accType1, 0, 197, Short.MAX_VALUE)
                        .addComponent(ssn2)
                        .addComponent(sAcc2, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                        .addComponent(uid1)
                        .addComponent(pinText1))
                    .addComponent(dateChooserCombo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        Panel4Layout.setVerticalGroup(
            Panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel4Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(Panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(fname1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel47))
                .addGap(26, 26, 26)
                .addGroup(Panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel49)
                    .addComponent(lname1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(Panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel51)
                    .addComponent(addr1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel53)
                    .addComponent(city1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel54)
                    .addComponent(state1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(Panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(country1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel46))
                .addGap(47, 47, 47)
                .addGroup(Panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(dateChooserCombo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(Panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(ssn2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(Panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel50)
                    .addComponent(accType1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(Panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel52)
                    .addComponent(cAcc2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(Panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sAcc2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(Panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(uidVar1)
                    .addComponent(uid1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pin2)
                    .addComponent(pinText1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(createButton1)
                .addContainerGap(73, Short.MAX_VALUE))
        );

        ScrollPanel.setViewportView(Panel4);

        basePanel.add(ScrollPanel, "card7");

        jLabel36.setText("Enter User ID :");

        freezeButton.setText("Freeze!");
        freezeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                freezeButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Panel3Layout = new javax.swing.GroupLayout(Panel3);
        Panel3.setLayout(Panel3Layout);
        Panel3Layout.setHorizontalGroup(
            Panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel3Layout.createSequentialGroup()
                .addGroup(Panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel3Layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(freezeButton)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(Panel3Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel36)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 198, Short.MAX_VALUE)
                        .addComponent(uidText, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        Panel3Layout.setVerticalGroup(
            Panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel3Layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addGroup(Panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel36)
                    .addComponent(uidText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 258, Short.MAX_VALUE)
                .addComponent(freezeButton)
                .addGap(115, 115, 115))
        );

        basePanel.add(Panel3, "card2");

        cbText.setEditable(false);

        jLabel29.setText("Address :");

        sbText.setEditable(false);

        addrText.setEditable(false);
        addrText.setColumns(20);
        addrText.setRows(5);
        jScrollPane1.setViewportView(addrText);

        jButton3.setText("OK");

        jLabel30.setText("Contact No. :");

        cntText.setEditable(false);

        jLabel31.setText("Checkings AccNo.:");

        cAcc.setEditable(false);

        jLabel32.setText("Checkings :");

        jLabel33.setText("Savings :");

        jLabel34.setText("Name :");

        jLabel35.setText("Balance");

        nameText.setEditable(false);

        savings.setText("Savings AccNo.:");

        javax.swing.GroupLayout Panel21Layout = new javax.swing.GroupLayout(Panel21);
        Panel21.setLayout(Panel21Layout);
        Panel21Layout.setHorizontalGroup(
            Panel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel21Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(Panel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel21Layout.createSequentialGroup()
                        .addComponent(savings)
                        .addGroup(Panel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Panel21Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel35)
                                .addGap(222, 222, 222))
                            .addGroup(Panel21Layout.createSequentialGroup()
                                .addGap(61, 61, 61)
                                .addComponent(sAcc, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(Panel21Layout.createSequentialGroup()
                        .addGroup(Panel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel34)
                            .addComponent(jLabel29)
                            .addComponent(jLabel30)
                            .addComponent(jLabel31)
                            .addComponent(jLabel32)
                            .addComponent(jLabel33))
                        .addGap(43, 43, 43)
                        .addGroup(Panel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1)
                            .addComponent(nameText)
                            .addComponent(cntText)
                            .addComponent(cAcc)
                            .addComponent(cbText)
                            .addComponent(sbText))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3)
                        .addContainerGap())))
        );
        Panel21Layout.setVerticalGroup(
            Panel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel21Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(Panel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(nameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel34))
                .addGap(18, 18, 18)
                .addGroup(Panel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel29)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(Panel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel30)
                    .addComponent(cntText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(Panel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31)
                    .addComponent(cAcc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Panel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel21Layout.createSequentialGroup()
                        .addComponent(sAcc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                        .addComponent(jLabel35))
                    .addGroup(Panel21Layout.createSequentialGroup()
                        .addComponent(savings)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Panel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel32, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cbText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addGroup(Panel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel33)
                    .addComponent(sbText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3))
                .addContainerGap(98, Short.MAX_VALUE))
        );

        basePanel.add(Panel21, "card2");

        jLabel37.setText("Enter User ID. :");

        retrieveButton.setText("Retrieve!!");
        retrieveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                retrieveButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Panel2Layout = new javax.swing.GroupLayout(Panel2);
        Panel2.setLayout(Panel2Layout);
        Panel2Layout.setHorizontalGroup(
            Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel2Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel37)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 175, Short.MAX_VALUE)
                .addComponent(jTextField32, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(Panel2Layout.createSequentialGroup()
                .addGap(195, 195, 195)
                .addComponent(retrieveButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Panel2Layout.setVerticalGroup(
            Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel2Layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addGroup(Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel37)
                    .addComponent(jTextField32, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addComponent(retrieveButton)
                .addContainerGap(335, Short.MAX_VALUE))
        );

        basePanel.add(Panel2, "card2");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(basePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(basePanel, javax.swing.GroupLayout.DEFAULT_SIZE, 528, Short.MAX_VALUE)))
                .addContainerGap())
        );

        icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UIComponents/piggy_bank_icon.jpg"))); // NOI18N

        logoutButton.setText("Logout");
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(displayName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logoutButton)
                .addGap(33, 33, 33))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(icon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(9, 9, 9))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(logoutButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(displayName)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(icon)
                        .addGap(15, 15, 15))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void createActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createActionPerformed
       basePanel.removeAll();
        basePanel.repaint();
        basePanel.revalidate();
        
        basePanel.add(ScrollPanel);
        basePanel.repaint();
        basePanel.revalidate();
    }//GEN-LAST:event_createActionPerformed

    private void viewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewActionPerformed
        basePanel.removeAll();
        basePanel.repaint();
        basePanel.revalidate();
        
        basePanel.add(Panel2);
        basePanel.repaint();
        basePanel.revalidate();
       
        uid=uidText.getText();
        
        
        
        
    }//GEN-LAST:event_viewActionPerformed

    private void freezeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_freezeActionPerformed
        basePanel.removeAll();
        basePanel.repaint();
        basePanel.revalidate();
        
        basePanel.add(Panel3);
        basePanel.repaint();
        basePanel.revalidate();
    }//GEN-LAST:event_freezeActionPerformed

    private void createButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createButton1ActionPerformed
      
        
        fn=fname1.getText();
        ln=lname1.getText();
        add=addr1.getText();
        cit=city1.getText();
        cntry=country1.getText();
        date=dateChooserCombo1.getSelectedDate();
        aType=accType1.getSelectedItem().toString();
        cAcc1=cAcc2.getText();
        sAcc1=sAcc2.getText();
        
        ssn1=Integer.parseInt(ssn2.getText());
        uid=uid1.getText();
        pin1=Integer.parseInt(pinText1.getText());
       
                
        
        System.out.println("Contacting Server");
            Socket client = null;
        try {
            client = new Socket("localhost", 6000);
        } catch (IOException ex) {
            Logger.getLogger(admin.class.getName()).log(Level.SEVERE, null, ex);
        }
            ObjectOutputStream outputStream = null;
        try {
            outputStream = new ObjectOutputStream(client.getOutputStream());
        } catch (IOException ex) {
            Logger.getLogger(admin.class.getName()).log(Level.SEVERE, null, ex);
        }
            ObjectInputStream inputStream = null;
        try {
            inputStream = new ObjectInputStream(client.getInputStream());
        } catch (IOException ex) {
            Logger.getLogger(admin.class.getName()).log(Level.SEVERE, null, ex);
        }
            RequestResponseMessenger sendObj=new RequestResponseMessenger();
            
            sendObj.setMessage("createUser");
            System.out.println("About to send");
            sendObj.setFname(fn);
            sendObj.setLname(ln);
            sendObj.setAddr(add+cit+cntry);
     
            sendObj.setSsn(ssn1);
            sendObj.setDate(date);
            sendObj.setUid(uid);
            sendObj.setPin(pin1);
            sendObj.setChk_acc_no(cAcc1);
            sendObj.setSav_acc_no(sAcc1);
         
            if(aType.equalsIgnoreCase("checkings")){
                
                sendObj.setaType("Checkings");
                sendObj.setChk_acc_no(cAcc1);
            
            }
            else 
                if(aType.equalsIgnoreCase("savings")){
                    sendObj.setaType("Savings");
                    sendObj.setSav_acc_no(sAcc1);
                    
                }
                else
                   if(aType.equalsIgnoreCase("both")){
                {
                   sendObj.setaType("Checkings,Savings");
                    sendObj.setChk_acc_no(cAcc1);
                    sendObj.setSav_acc_no(sAcc1);
                }
                  
        try {
            outputStream.writeObject(sendObj);
        } catch (IOException ex) {
            Logger.getLogger(admin.class.getName()).log(Level.SEVERE, null, ex);
        }
            System.out.println("Sent");
        try {
            RequestResponseMessenger recvObj = (RequestResponseMessenger) inputStream.readObject();
            if(recvObj.getMessage().equalsIgnoreCase("created")){
                    
                System.out.println("received");
                JOptionPane.showMessageDialog(jPanel1, "User created!!");
            }
        } catch (IOException | ClassNotFoundException ex) {
            Logger.getLogger(admin.class.getName()).log(Level.SEVERE, null, ex);
        }
            
        System.out.println("received");
            //System.out.println(recvObj.getMessage());
            
      
            
      
                   }   
    }//GEN-LAST:event_createButton1ActionPerformed

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
    
        OnlineBanking ob=new OnlineBanking();
       ob.setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_logoutButtonActionPerformed

    private void retrieveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_retrieveButtonActionPerformed
        // TODO add your handling code here:
        
        
        basePanel.removeAll();
        basePanel.repaint();
        basePanel.revalidate();
        
        basePanel.add(Panel21);
        basePanel.repaint();
        basePanel.revalidate();
        
        

        System.out.println("Contacting Server");
        Socket client = null;
        try {
            client = new Socket("localhost", 6000);
        } catch (IOException ex) {
            Logger.getLogger(UserFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        ObjectOutputStream outputStream = null;
        try {
            outputStream = new ObjectOutputStream(client.getOutputStream());
        } catch (IOException ex) {
            Logger.getLogger(UserFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        ObjectInputStream inputStream = null;
        try {
            inputStream = new ObjectInputStream(client.getInputStream());
        } catch (IOException ex) {
            Logger.getLogger(UserFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        RequestResponseMessenger sendObj = new RequestResponseMessenger();
        sendObj.setMessage("retrieve");
        sendObj.setUid(uid);
        

        try {
            outputStream.writeObject(sendObj);

            System.out.println("Sent");
            RequestResponseMessenger recvObj = (RequestResponseMessenger) inputStream.readObject();
            fn=recvObj.getFname();
            ln=recvObj.getLname();
            add=recvObj.getAddr();
            
            sAcc1=recvObj.getSav_acc_no();
            cAcc1=recvObj.getChk_acc_no();
            System.out.println(fn+ln+add+sAcc1+cAcc1);
            String name=fn+ln;
            nameText.setText(name);
            addrText.setText(add);
           
            sAcc.setText(sAcc1);
            cAcc.setText(cAcc1);
            cbText.setText(recvObj.getChk_bal());
            sbText.setText(recvObj.getSav_bal());
            
            
            
            System.out.println("Details Displayed!!");
            
            
            

        } catch (IOException ex) {
            Logger.getLogger(UserFrame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(admin.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_retrieveButtonActionPerformed

    private void freezeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_freezeButtonActionPerformed
        // TODO add your handling code here:
        
        uid=uidText.getText();
        
        System.out.println("Contacting Server");
        Socket client = null;
        try {
            client = new Socket("localhost", 6000);
        } catch (IOException ex) {
            Logger.getLogger(UserFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        ObjectOutputStream outputStream = null;
        try {
            outputStream = new ObjectOutputStream(client.getOutputStream());
        } catch (IOException ex) {
            Logger.getLogger(UserFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        ObjectInputStream inputStream = null;
        try {
            inputStream = new ObjectInputStream(client.getInputStream());
        } catch (IOException ex) {
            Logger.getLogger(UserFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        RequestResponseMessenger sendObj = new RequestResponseMessenger();
        sendObj.setMessage("freeze");
        sendObj.setUid(uid);
        

        try {
            outputStream.writeObject(sendObj);

            System.out.println("Sent");
            RequestResponseMessenger recvObj = (RequestResponseMessenger) inputStream.readObject();
            
            if(recvObj.getMessage().equalsIgnoreCase("freezed"))
                JOptionPane.showMessageDialog(jPanel1, "Freezed!!");
            
        } catch (IOException ex) {
            Logger.getLogger(UserFrame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(UserFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
    }//GEN-LAST:event_freezeButtonActionPerformed

    private void ssn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ssn2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ssn2ActionPerformed

    /*
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new admin().setVisible(true);
//                
//                
//            }
//        });
//  }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Panel2;
    private javax.swing.JPanel Panel21;
    private javax.swing.JPanel Panel3;
    private javax.swing.JPanel Panel4;
    private javax.swing.JScrollPane ScrollPanel;
    private javax.swing.JComboBox accType1;
    private javax.swing.JTextField addr1;
    private javax.swing.JTextArea addrText;
    private javax.swing.JPanel basePanel;
    private javax.swing.JTextField cAcc;
    private javax.swing.JTextField cAcc2;
    private javax.swing.JTextField cbText;
    private javax.swing.JTextField city1;
    private javax.swing.JTextField cntText;
    private javax.swing.JTextField country1;
    private javax.swing.JButton create;
    private javax.swing.JButton createButton1;
    private datechooser.beans.DateChooserCombo dateChooserCombo1;
    private javax.swing.JLabel displayName;
    private javax.swing.JPanel firstPanel;
    private javax.swing.JTextField fname1;
    private javax.swing.JButton freeze;
    private javax.swing.JButton freezeButton;
    private javax.swing.JLabel icon;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField32;
    private javax.swing.JTextField lname1;
    private javax.swing.JButton logoutButton;
    private javax.swing.JTextField nameText;
    private javax.swing.JLabel pin2;
    private javax.swing.JPasswordField pinText1;
    private javax.swing.JButton retrieveButton;
    private javax.swing.JTextField sAcc;
    private javax.swing.JTextField sAcc2;
    private javax.swing.JLabel savings;
    private javax.swing.JTextField sbText;
    private javax.swing.JTextField ssn2;
    private javax.swing.JTextField state1;
    private javax.swing.JTextField uid1;
    private javax.swing.JTextField uidText;
    private javax.swing.JLabel uidVar1;
    private javax.swing.JButton view;
    // End of variables declaration//GEN-END:variables
}
